const en_US = {
  销售协同管理系统: 'Sales Collaboration Management system',
  项目状态: 'project status',
  全部: 'all',
  待采购: 'to be purchased',
  已报价: 'have quoted the price',
  已确认: 'acknowledged',
  已签合同: 'Signed contract',
  结束: 'finish',
  中止: 'suspend',
  查询: 'inquire',
  重置: 'reset',
  展开: 'Expand',
  收起: 'Collapse',
  项目编号: 'Project Number',
  项目名称: 'Project Name',
  客户: 'Customer',
  业务员: 'Salesperson',
  状态: 'Status',
  询价供应商: 'Quotation Suppliers',
  预计采购日期: 'Estimated Purchase Date',
  项目类型: 'Project Type',
  框架合同: 'Framework Contract',
  即期合同: 'Spot Contract',
  预估金额: 'Estimated Amount',
  万元: 'Ten Thousand Yuan',
  付款方式: 'Payment Method',
  创建时间: 'Creation Time',
  创建者: 'Creator',
  操作: 'Operation',
  编辑: 'Edit',
  更多: 'More',
  升级: 'Upgrade',
  删除: 'Delete',
  删除商机: 'Delete Business Opportunity',
  '确定删除该商机吗？数据删除后将无法恢复！':
    'Are you sure you want to delete this business opportunity? The data cannot be recovered after deletion!',
  创建项目: 'Create Project',
  导出列表: 'Export List',
  客户付款方: 'Customer Payer',
  我司签约: 'Our Company Contract',
}

export default en_US
